name: micro-dask-tutorial-widsPS22
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - dask==2022.1.0
  - distributed==2022.1.0
  - jupyterlab==3.3.2
  - dask-labextension==5.2.0
  - python-graphviz==0.19.1
  - numpy==1.21.5
  - pandas=1.3.5
  - fsspec==2022.3.0
  - pyarrow==7.0.0
  - ipywidgets==7.7.0
  - plotly==5.7.0
  - matplotlib==3.5.1
  - pip
  - pip:
    - sodapy==2.1.1
    # for Prophet package
    - pystan==2.19.1.1
    - prophet==1.0.1
    - Cython==0.29.28
    - cmdstanpy==0.9.68
    - LunarCalendar==0.0.9
    - convertdate==2.4.0
    - holidays==0.13
    - setuptools-git==1.2
    - tqdm==4.64.0
